---
###############################################################
#             Authelia Users Database for Homelab             #
###############################################################

users:
  admin:
    displayname: "Homelab Administrator"
    password: "$argon2id$v=19$m=65536,t=3,p=4$VC25Bq3fZdzzJ286AtaavA$J7kw6LK/CYRP0wSRztlfVNlf43eyR4xXxcvIgUOAjYg"
    email: "admin@mew.lab"
    groups:
      - "admins"
      - "devops"

  mew:
    displayname: "Mew"
    password: "$argon2id$v=19$m=65536,t=3,p=4$VC25Bq3fZdzzJ286AtaavA$J7kw6LK/CYRP0wSRztlfVNlf43eyR4xXxcvIgUOAjYg"
    email: "mew@mew.lab"
    groups:
      - "admins"
      - "devops"
