---
###############################################################
#             Authelia Users Database for Homelab             #
###############################################################

users:
  admin:
    displayname: "Homelab Administrator"
    password: "$argon2id$v=19$m=65536,t=3,p=4$iIz2EvpETnkeYEF3DaEf4w$d4LzT3xi6UKvg2uvY3S2R2XKuwLIvcfSgA4vZ3UxBaQ"
    email: "admin@mew.lab"
    groups:
      - "admins"
      - "devops"

  mew:
    displayname: "Mew"
    password: "$argon2id$v=19$m=65536,t=3,p=4$iIz2EvpETnkeYEF3DaEf4w$d4LzT3xi6UKvg2uvY3S2R2XKuwLIvcfSgA4vZ3UxBaQ"
    email: "mew@mew.lab"
    groups:
      - "admins"
      - "devops"
