---
###############################################################
#             Authelia Users Database for Homelab             #
###############################################################

users:
  admin:
    displayname: "Homelab Administrator"
    password: "$argon2id$v=19$m=65536,t=3,p=4$dK86UGVxN6RBbpa5zPqjUw$KIzY8G93DjqmiNGbtjp7oSRdbZGR8xBHemE972MNjLw"
    email: "admin@mew.lab"
    groups:
      - "admins"
      - "devops"

  mew:
    displayname: "Mew"
    password: "$argon2id$v=19$m=65536,t=3,p=4$dK86UGVxN6RBbpa5zPqjUw$KIzY8G93DjqmiNGbtjp7oSRdbZGR8xBHemE972MNjLw"
    email: "mew@mew.lab"
    groups:
      - "admins"
      - "devops"
