name: Debug Server
on:
  push:
    paths:
      - 'debug.txt'
jobs:
  debug:
    runs-on: self-hosted
    steps:
      - name: Expand LVM natively
        run: |
          docker run --rm --privileged --pid=host ubuntu nsenter -t 1 -m -u -n -i sh -c "lvextend -l +100%FREE /dev/mapper/ubuntu--vg-ubuntu--lv && resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv"
          df -h /
